name: opensource_qwkin_dart

versioning:
  mode: independent

packages:
  - packages/**

scripts:
  # Analyze the project for Dart analysis issues.
  #  - Requires `pub global activate tuneup`.
  analyze: >
    melos exec -c 1 --fail-fast -- \
      flutter analyze .

  # Formats the code of all packages (Java, Objective-C, and Dart).
  #  - Requires `flutter_plugin_tools` (`pub global activate flutter_plugin_tools`).
  #  - Requires `git`.
  #  - Requires `clang-format` (can be installed via Brew on MacOS / apt on Ubuntu based).
  format: pub global run flutter_plugin_tools format --shardIndex 0 --shardCount 3

  format:dart: flutter format .

  test:torch:controller: >
    melos exec -c 1 --fail-fast --scope="torch_controller" -- \
    flutter test --coverage

  test:storage:controller: >
    melos exec -c 1 --fail-fast --scope="storage_controller" -- \
    flutter test --coverage

  ## BE CAREFUL USING THIS
  publish:packages: >
    melos exec -c 1 --fail-fast --ignore="*example*" -- \
    flutter pub publish --force

  # Additional cleanup lifecycle script, executed when `melos clean` is ran.
  postclean: >
    melos exec -- \
      flutter clean
      rm -rf ./build ./android/.gradle ./ios/.symlinks ./ios/Pods ./android/.idea ./.idea ./.dart-tool/build

  # Additional bootstrap lifecycle script
  postbootstrap: |
    tuneup --version || pub global activate tuneup

dev_dependencies:
  pedantic: 1.9.2

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.10.0"
