name: flutter_ca
description: A framework to implement clean architecture for flutter
version: 0.2.2
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  flutter_ca_domain: ^0.2.0
  flutter_ca_presentation: ^0.2.2
  flutter_ca_data: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
