name: torch_controller
description: A controller to manage torch/flash device resource. We give you access to native resources to toggle flashlight, to natively check torch status and more!
version: 1.0.0
homepage: https://github.com/4itworks/opensource_qwkin_dart

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.example.torch_controller
        pluginClass: TorchControllerPlugin
      ios:
        pluginClass: TorchControllerPlugin